[package]
name = "priority-inheriting-lock"
version = "0.1.0"
edition = "2021"
authors = ["Ryan Zoeller <rtzoeller@rtzoeller.com>"]
description = "A priority-inheriting lock based on Linux futexes"
categories = ["concurrency"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.126"
linux-futex = "0.1.1"
lock_api = "0.4.6"
once_cell = "1.12.0"
thread_local = "1.1.4"

[dev-dependencies]
nix = { version = "0.24.1", default-features = false, features = ["user"] }

[[test]]
name = "tests"
path = "tests/tests.rs"
