on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.69.0 # MSRV
        target:
          - aarch64-linux-android
          - x86_64-unknown-linux-gnu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - run: rustup toolchain add --profile=minimal ${{ matrix.rust }} --component clippy --component rustfmt

      - run: rustup target add --toolchain=${{ matrix.rust }} ${{ matrix.target }}

      - run: cargo +${{ matrix.rust }} build --target=${{ matrix.target }}

      - if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo +${{ matrix.rust }} test

      - if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo +${{ matrix.rust }} fmt --all --check

      - if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: cargo +${{ matrix.rust }} clippy -- -D warnings

  semver:
    name: Check semver (must manually inspect)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check semver (must manually inspect)
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          verbose: true
        continue-on-error: true
